definitions:
  models.AccountExecution:
    properties:
      accountId:
        example: 1234567890
        type: integer
      lots:
        example: 0.1
        type: number
      market:
        example: EUR
        type: string
      price:
        example: 1.23456
        type: number
      quote:
        example: USD
        type: string
      sellbuy:
        example: B
        type: string
      symbol:
        example: EURUSD
        type: string
      tradeId:
        example: "110101"
        type: string
      type:
        example: TRADE_OPEN
        type: string
    type: object
  models.Error:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Execution failed
        type: string
    type: object
  models.Execution:
    properties:
      accountId:
        type: integer
      error:
        type: string
      follower:
        type: string
      leaderId:
        type: string
      leaderTradeId:
        type: string
      lots:
        type: number
      market:
        type: string
      pl:
        type: number
      price:
        type: number
      quote:
        type: string
      sellbuy:
        type: string
      signal:
        type: string
      symbol:
        type: string
      tag:
        type: string
      time:
        type: string
      tradeId:
        type: string
      type:
        type: string
    type: object
  models.ExecutionResponse:
    properties:
      actOrderId:
        example: 11211
        type: integer
      success:
        example: true
        type: boolean
    type: object
  models.FollowRule:
    properties:
      active:
        type: boolean
      instrumentList:
        items:
          type: string
        type: array
      leaderCondOrders:
        type: boolean
      lotsMethod:
        type: string
      lotsValue:
        type: number
      maxLots:
        type: number
      maxLotsPerMarket:
        type: number
      reverseSignal:
        type: boolean
      slOnCapital:
        type: number
      slPips:
        type: integer
      slTrail:
        type: boolean
      tpOnCapital:
        type: number
      tpPips:
        type: integer
    type: object
  models.Follower:
    properties:
      account:
        type: integer
      active:
        type: boolean
      instrumentList:
        items:
          type: string
        type: array
      investAmount:
        type: number
      leader:
        type: string
      leaderCondOrders:
        type: boolean
      lotsMethod:
        type: string
      lotsValue:
        type: number
      maxLots:
        type: number
      maxLotsPerMarket:
        type: number
      platform:
        type: string
      reverseSignal:
        type: boolean
      slOnCapital:
        type: number
      slPips:
        type: integer
      slTrail:
        type: boolean
      tpOnCapital:
        type: number
      tpPips:
        type: integer
      uuid:
        type: string
    type: object
  models.FollowerSignalResponse:
    properties:
      error:
        type: string
      executionTimestamp:
        type: string
      follower:
        type: string
      followerTradeId:
        type: string
      lots:
        type: number
      market:
        type: string
      price:
        type: number
      quote:
        type: string
      sellbuy:
        type: string
      timestamp:
        type: string
      type:
        type: string
      uuid:
        type: string
    type: object
  models.Leader:
    properties:
      account:
        type: integer
      active:
        type: boolean
      firstName:
        type: string
      lastName:
        type: string
      platform:
        type: string
      uuid:
        type: string
    type: object
  models.NewSignal:
    properties:
      actTradeId:
        example: 123456789
        type: integer
      leader:
        example: 061fb59e-1585-4ce8-9a2e-73472e3f9962
        type: string
      lots:
        example: 0.01
        type: number
      market:
        example: EUR
        type: string
      price:
        example: 1.23456
        type: number
      quote:
        example: USD
        type: string
      sellbuy:
        example: S
        type: string
      symbol:
        example: EURUSD
        type: string
      tag:
        example: custom tag
        type: string
      tradeId:
        example: "1234567890"
        type: string
      type:
        example: TRADE_CLOSE
        type: string
    type: object
  models.NewSignalResponse:
    properties:
      signal:
        example: 8a67a268-0f9f-41dd-a88c-ed453ede218f
        type: string
      success:
        example: true
        type: boolean
    type: object
  models.RegisterFollower:
    properties:
      copyLeaderPositions:
        type: boolean
      instrumentList:
        items:
          type: string
        type: array
      investAmount:
        type: number
      leader:
        type: string
      leaderCondOrders:
        type: boolean
      lotsMethod:
        type: string
      lotsValue:
        type: number
      maxLots:
        type: number
      maxLotsPerMarket:
        type: number
      platform:
        type: string
      reverseSignal:
        type: boolean
      slOnCapital:
        type: number
      slPips:
        type: integer
      slTrail:
        type: boolean
      tpOnCapital:
        type: number
      tpPips:
        type: integer
      trader:
        type: integer
    type: object
  models.Signal:
    properties:
      actTradeId:
        type: integer
      executions:
        items:
          $ref: '#/definitions/models.SignalResult'
        type: array
      leader:
        type: string
      lots:
        type: number
      market:
        type: string
      price:
        type: number
      quote:
        type: string
      sellbuy:
        type: string
      signal:
        type: string
      symbol:
        type: string
      tag:
        type: string
      time:
        type: string
      tradeId:
        type: string
      type:
        type: string
    type: object
  models.SignalResult:
    properties:
      error:
        type: string
      follower:
        type: string
      lots:
        type: number
      order:
        type: integer
      price:
        type: number
      sellbuy:
        type: string
      timestamp:
        type: string
    type: object
  models.Success:
    properties:
      success:
        type: boolean
    type: object
  models.WsCloseTradePayload:
    properties:
      actTradeId:
        example: 50
        type: integer
      follower:
        example: d8fe1b86-a765-4f2d-ac47-65a79321a668
        type: string
      leader:
        example: 061fb59e-1585-4ce8-9a2e-73472e3f9962
        type: string
      price:
        example: 1.23456
        type: number
      signal:
        example: 7c79793b-f35e-4023-9c37-b45af2055931
        type: string
      time:
        example: "2020-09-29T23:59:59+08:00"
        type: string
      tradeId:
        example: "123456789"
        type: string
      type:
        example: TRADE_CLOSE
        type: string
    type: object
  models.WsCloseTradeResponse:
    properties:
      payload:
        $ref: '#/definitions/models.WsCloseTradePayload'
      type:
        example: signal
        type: string
    type: object
  models.WsLimitOrderPayload:
    properties:
      actTradeId:
        example: 50
        type: integer
      follower:
        example: d8fe1b86-a765-4f2d-ac47-65a79321a668
        type: string
      leader:
        example: 061fb59e-1585-4ce8-9a2e-73472e3f9962
        type: string
      signal:
        example: 7c79793b-f35e-4023-9c37-b45af2055931
        type: string
      time:
        example: "2020-09-29T23:59:59+08:00"
        type: string
      tradeId:
        example: "123456789"
        type: string
      type:
        example: LIMIT_UPDATE
        type: string
    type: object
  models.WsLimitOrderResponse:
    properties:
      payload:
        $ref: '#/definitions/models.WsLimitOrderPayload'
      type:
        example: signal
        type: string
    type: object
  models.WsOpenTradePayload:
    properties:
      accountId:
        example: 12345
        type: integer
      follower:
        example: d8fe1b86-a765-4f2d-ac47-65a79321a668
        type: string
      leader:
        example: 061fb59e-1585-4ce8-9a2e-73472e3f9962
        type: string
      leaderOrderId:
        example: "123456"
        type: string
      lots:
        example: 0.01
        type: number
      market:
        example: EURUSD
        type: string
      price:
        example: 1.23456
        type: number
      quote:
        example: USD
        type: string
      sellbuy:
        example: B
        type: string
      signal:
        example: 7c79793b-f35e-4023-9c37-b45af2055931
        type: string
      symbol:
        example: EURUSD
        type: string
      tag:
        example: custom tag
        type: string
      time:
        example: "2020-09-29T23:59:59+08:00"
        type: string
      type:
        example: TRADE_OPEN
        type: string
    type: object
  models.WsOpenTradeResponse:
    properties:
      payload:
        $ref: '#/definitions/models.WsOpenTradePayload'
      type:
        example: signal
        type: string
    type: object
  models.WsStopOrderPayload:
    properties:
      actTradeId:
        example: 50
        type: integer
      follower:
        example: d8fe1b86-a765-4f2d-ac47-65a79321a668
        type: string
      leader:
        example: 061fb59e-1585-4ce8-9a2e-73472e3f9962
        type: string
      price:
        example: 1.23456
        type: number
      signal:
        example: 7c79793b-f35e-4023-9c37-b45af2055931
        type: string
      time:
        example: "2020-09-29T23:59:59+08:00"
        type: string
      tradeId:
        example: "123456789"
        type: string
      type:
        example: STOP_UPDATE
        type: string
    type: object
  models.WsStopOrderResponse:
    properties:
      payload:
        $ref: '#/definitions/models.WsStopOrderPayload'
      type:
        example: signal
        type: string
    type: object
host: zulu-ftl.acttrader.com
info:
  contact:
    email: support@acttrader.com
    name: ActTrader Support
  description: This is a FTL API based on the OpenAPI 3.0 specification.
  title: FTL for Zulu
  version: "1.0"
paths:
  /account/execution:
    post:
      consumes:
      - application/json
      description: Account trade execution
      parameters:
      - description: Execution data JSON
        in: body
        name: execution
        required: true
        schema:
          $ref: '#/definitions/models.AccountExecution'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ExecutionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      tags:
      - account
  /follower/execution:
    post:
      consumes:
      - application/json
      description: Register follower execution
      parameters:
      - description: Execution data JSON
        in: body
        name: execution
        required: true
        schema:
          $ref: '#/definitions/models.Execution'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ExecutionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      tags:
      - follower
  /follower/list:
    get:
      description: Get followers list
      parameters:
      - description: leader uuid
        in: query
        name: leader
        type: string
      - description: follower uuid
        in: query
        name: follower
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Follower'
            type: array
      tags:
      - follower
  /follower/modify:
    put:
      consumes:
      - application/json
      description: Update follower
      parameters:
      - description: Follower settings JSON
        in: body
        name: follower
        required: true
        schema:
          $ref: '#/definitions/models.FollowRule'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.FollowRule'
      tags:
      - follower
  /follower/register:
    post:
      consumes:
      - application/json
      description: Register new follower
      parameters:
      - description: Follower settings JSON
        in: body
        name: follower
        required: true
        schema:
          $ref: '#/definitions/models.RegisterFollower'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Follower'
      tags:
      - follower
  /follower/signals:
    get:
      description: Get follower signals
      parameters:
      - description: follower uuid
        in: query
        name: follower
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.FollowerSignalResponse'
            type: array
      tags:
      - follower
  /follower/unregsiter:
    delete:
      description: Unregister follower
      parameters:
      - description: follower uuid
        in: query
        name: uuid
        required: true
        type: string
      - description: 'closeAccount flag: Y or N'
        in: query
        name: closeAccount
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Success'
      tags:
      - follower
  /leader/list:
    get:
      description: Get leaders list
      parameters:
      - description: 'Active flag: Y or N'
        in: query
        name: active
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Leader'
            type: array
      tags:
      - leader
  /leader/register:
    post:
      description: Register new leader
      parameters:
      - description: ActTrader account ID
        in: query
        name: account
        required: true
        type: string
      - description: Broker platform name
        in: query
        name: platform
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Leader'
      tags:
      - leader
  /leader/signal:
    post:
      description: Register leader signal
      parameters:
      - description: Signal data JSON
        in: body
        name: signal
        required: true
        schema:
          $ref: '#/definitions/models.NewSignal'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.NewSignalResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      tags:
      - leader
  /leader/signals:
    get:
      description: Get leader signals
      parameters:
      - description: leader uuid
        in: query
        name: leader
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Signal'
            type: array
      tags:
      - leader
  /leader/unregister:
    delete:
      description: Unregister leader
      parameters:
      - description: leader uuid
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Success'
      tags:
      - leader
  /ws:
    get:
      description: WebSocket connection for real-time notifications
      responses:
        "200":
          description: Example response for opening a trade
          schema:
            $ref: '#/definitions/models.WsOpenTradeResponse'
        "201":
          description: Example response for closing a trade
          schema:
            $ref: '#/definitions/models.WsCloseTradeResponse'
        "202":
          description: Example response for limit order updates
          schema:
            $ref: '#/definitions/models.WsLimitOrderResponse'
        "203":
          description: Example response for stop order updates
          schema:
            $ref: '#/definitions/models.WsStopOrderResponse'
      tags:
      - websocket
schemes:
- https
swagger: "2.0"
